### ISSUE TITLE
Integrate Data Management Portal

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal-2205#38]
Consider a link to http://federaldatasteward.scienceprogram.cloud:8080/signup - [a deployment of Data Stewardship Wizard](https://github.com/ds-wizard).

Would be nice to have a tile in each project. I believe all we would need to figure out is how to automate authentication there.

**Comment by Lynnehunks** [comment]
We'll need to consider instructions for users on when to use this. And eventually we'd like to use the data from the DMP as metadata on the files in the storage project. Not there yet

**Comment by Lynnehunks** [comment]
https://github.com/ssc-sp/datahub-portal/issues/2
