### ISSUE TITLE
Databricks users showing in wrong location

### ISSUE THREAD

**Issue by Lynnehunks** [ssc-sp/datahub-portal-2205#56]
**Describe the bug / issue**
Guillaume Bilodeau reported this. 

Collabortor Hervé Van der Heyden is under my project for databricks seems he sees Emilie and others in users but when I'm in I just see myself? Seems working with data storage but the databricks is different

**Comment by Lynnehunks** [comment]
Per Ilango: inside the portal, the Databricks link was referencing an older instance of databricks (which you happened to have access)l. I've corrected the link so it will take you to the correct workspace now. Please try again and let me know. Thanks.

**Comment by Lynnehunks** [comment]
[2:02 p.m.] Bilodeau, Guillaume (CFIA/ACIA)
Yes seems to be working now I have access to it too.

**Comment by yjmrobert** [comment]
@Lynnehunks I'll have to look into this -- I'm not sure where that's even set
